version: '3'
services:
  nginx:
    build: ./.docker/dev/nginx
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./app:/application
      - ./.docker/dev/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./.docker/dev/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  php:
    build: ./.docker/dev/php
    image: php
    volumes:
      - ./app:/application
      - ./.docker/dev/php/php.ini:/usr/local/etc/php/php.ini
    links:
      - db
  db:
    image: postgres:10.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: myDb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: test
    volumes:
      - ./.docker/data/postgres/:/var/lib/postgresql/data
 